package teamprovision

import "testing"

func deltaTestRole(role,family string,capabilities ...string)RoleSpec{return RoleSpec{Role:role,Family:family,DisplayName:role,Description:role,Capabilities:capabilities,Responsibilities:[]string{"deliver"}}}

func TestBuildControlledTeamDeltaDefaultsToAddOnly(t *testing.T){backend:=deltaTestRole(RoleBackendEngineer,"backend","go","api");mobile:=deltaTestRole(RoleMobileEngineer,"mobile","ios");delta:=BuildControlledTeamDelta(Plan{Roles:[]RoleSpec{backend}},Plan{Roles:[]RoleSpec{mobile}});if !delta.AddOnly||delta.RequiresApproval{t.Fatalf("expected add-only delta: %#v",delta)};keep,add:=false,false;for _,op:=range delta.Operations{if op.Role==RoleBackendEngineer&&op.Operation==TeamDeltaKeepAgent{keep=true};if op.Role==RoleMobileEngineer&&op.Operation==TeamDeltaAddAgent{add=true};if op.Operation==TeamDeltaRemoveAgent{t.Fatalf("replan inferred removal: %#v",op)}};if !keep||!add{t.Fatalf("expected KEEP backend and ADD mobile: %#v",delta.Operations)}}
func TestValidateExplicitTeamDeltaRemovalRequiresApproval(t *testing.T){backend:=deltaTestRole(RoleBackendEngineer,"backend","go");delta,err:=ValidateExplicitTeamDelta(TeamDelta{AddOnly:true,Operations:[]TeamDeltaOperation{{Operation:TeamDeltaRemoveAgent,Role:backend.Role,Before:&backend}}});if err!=nil{t.Fatalf("ValidateExplicitTeamDelta() error = %v",err)};if !delta.RequiresApproval||delta.AddOnly{t.Fatalf("explicit removal must require approval: %#v",delta)}}
func TestAnalyzeCapabilityImpactOnlyRequestsMissingCapability(t *testing.T){mobile:=deltaTestRole(RoleMobileEngineer,"mobile","ios","swift");plan:=Plan{Roles:[]RoleSpec{mobile}};covered:=AnalyzeCapabilityImpact(plan,[]CapabilityRequirement{{Family:"mobile",Capabilities:[]string{"ios"}}});if !covered.ExistingTeamSufficient||len(covered.Missing)!=0{t.Fatalf("existing iOS capability should be sufficient: %#v",covered)};missing:=AnalyzeCapabilityImpact(plan,[]CapabilityRequirement{{Family:"mobile",Capabilities:[]string{"android"}}});if missing.ExistingTeamSufficient||len(missing.Missing)!=1||missing.Missing[0].Capabilities[0]!="android"{t.Fatalf("only missing Android capability should trigger reconciliation: %#v",missing)}}
