package projectorchestration

import "testing"

func changeTestNode(key,title string)NodeSpec{return NodeSpec{Key:key,Kind:NodeProduct,Title:title,Description:title,Priority:1,RequiredCapabilities:[]string{"planning"},AcceptanceCriteria:[]string{"accepted"},Risk:RiskLow,MaxAttempts:3}}
func changeTestPlan(nodes ...NodeSpec)Plan{return Plan{Version:CurrentPlanVersion,Goal:"Ship a changeable project",Specification:Specification{Summary:"A project that can evolve safely",Requirements:[]string{"Preserve logical work identity"},DefinitionOfDone:[]string{"Approved changes are traceable"}},Policy:DefaultPolicy(),Nodes:nodes}}

func TestApplyPlanMutationRenamePreservesLogicalIdentityAndEdges(t *testing.T){
	first:=changeTestNode("discover","Discover");second:=changeTestNode("design","Design");plan:=changeTestPlan(first,second);plan.Edges=[]EdgeSpec{{From:"discover",To:"design",Type:DependencyHard}};nodes:=[]LogicalPlanNode{{LogicalNodeID:"11111111-1111-1111-1111-111111111111",Spec:first,Status:"completed"},{LogicalNodeID:"22222222-2222-2222-2222-222222222222",Spec:second,Status:"pending"}};renamed:=first;renamed.Key="discovery";renamed.Title="Product discovery"
	result,err:=ApplyPlanMutation(plan,nodes,[]PlanMutationOperation{{Operation:MutationUpdateNode,TargetLogicalNodeID:nodes[0].LogicalNodeID,Node:&renamed}});if err!=nil{t.Fatalf("ApplyPlanMutation() error = %v",err)};found:=false;for _,node:=range result.Nodes{if node.Spec.Key=="discovery"{found=true;if node.LogicalNodeID!=nodes[0].LogicalNodeID{t.Fatalf("rename changed logical id: got %s want %s",node.LogicalNodeID,nodes[0].LogicalNodeID)};if node.Status!="completed"{t.Fatalf("rename lost execution state: %s",node.Status)}}};if !found{t.Fatal("renamed node not found")};if len(result.Plan.Edges)!=1||result.Plan.Edges[0].From!="discovery"||result.Plan.Edges[0].To!="design"{t.Fatalf("rename did not rewrite edges: %#v",result.Plan.Edges)}
}

func TestApplyPlanMutationRemoveAddCreatesNewLogicalIdentity(t *testing.T){
	old:=changeTestNode("feature","Old feature");oldID:="11111111-1111-1111-1111-111111111111";replacement:=changeTestNode("feature_v2","Replacement feature");result,err:=ApplyPlanMutation(changeTestPlan(old),[]LogicalPlanNode{{LogicalNodeID:oldID,Spec:old,Status:"completed"}},[]PlanMutationOperation{{Operation:MutationRemoveNode,TargetLogicalNodeID:oldID},{Operation:MutationAddNode,Node:&replacement}});if err!=nil{t.Fatalf("ApplyPlanMutation() error = %v",err)};if len(result.Removed)!=1||result.Removed[0].LogicalNodeID!=oldID{t.Fatalf("removed mismatch: %#v",result.Removed)};for _,node:=range result.Nodes{if node.Spec.Key==replacement.Key{if node.LogicalNodeID==""||node.LogicalNodeID==oldID{t.Fatalf("replacement must receive new identity: %q",node.LogicalNodeID)};return}};t.Fatal("replacement node not found")
}

func TestAnalyzeChangeImpactRunningCancellationRequiresApproval(t *testing.T){node:=changeTestNode("feature","Feature");logical:=LogicalPlanNode{LogicalNodeID:"11111111-1111-1111-1111-111111111111",Spec:node,Status:"running"};policy:=DefaultPolicy();policy.Autonomy=AutonomyClosedLoop;impact:=AnalyzeChangeImpact(ChangeRemoveFeature,[]PlanMutationOperation{{Operation:MutationRemoveNode,TargetLogicalNodeID:logical.LogicalNodeID}},[]LogicalPlanNode{logical},policy);if impact.Level!=ImpactHigh||!impact.RequiresApproval||impact.AutoApplyAllowed{t.Fatalf("unexpected impact: %#v",impact)}}
func TestAnalyzeChangeImpactCompletedProductionInvalidationIsDestructive(t *testing.T){node:=changeTestNode("deploy","Deploy");node.Kind=NodeDeploy;logical:=LogicalPlanNode{LogicalNodeID:"11111111-1111-1111-1111-111111111111",Spec:node,Status:"completed"};impact:=AnalyzeChangeImpact(ChangeFeature,[]PlanMutationOperation{{Operation:MutationRemoveNode,TargetLogicalNodeID:logical.LogicalNodeID}},[]LogicalPlanNode{logical},DefaultPolicy());if impact.Level!=ImpactDestructive||!impact.RequiresApproval{t.Fatalf("unexpected impact: %#v",impact)}}
func TestAnalyzeChangeImpactLowClosedLoopCanAutoApply(t *testing.T){node:=changeTestNode("feature","Feature");logical:=LogicalPlanNode{LogicalNodeID:"11111111-1111-1111-1111-111111111111",Spec:node,Status:"pending"};updated:=node;updated.Title="Feature wording";policy:=DefaultPolicy();policy.Autonomy=AutonomyClosedLoop;impact:=AnalyzeChangeImpact(ChangeFeature,[]PlanMutationOperation{{Operation:MutationUpdateNode,TargetLogicalNodeID:logical.LogicalNodeID,Node:&updated}},[]LogicalPlanNode{logical},policy);if impact.Level!=ImpactLow||impact.RequiresApproval||!impact.AutoApplyAllowed{t.Fatalf("unexpected impact: %#v",impact)}}
func TestChangeRequestStateMachine(t *testing.T){allowed:=[][2]ChangeRequestState{{ChangeReceived,ChangeAnalyzing},{ChangeAnalyzing,ChangeProposalReady},{ChangeProposalReady,ChangeApprovalRequired},{ChangeApprovalRequired,ChangeApproved},{ChangeApproved,ChangeApplying},{ChangeApplying,ChangeApplied}};for _,pair:=range allowed{if !CanTransitionChangeRequest(pair[0],pair[1]){t.Fatalf("expected transition %s -> %s",pair[0],pair[1])}};if CanTransitionChangeRequest(ChangeReceived,ChangeApplied){t.Fatal("received -> applied must not bypass analysis")}}
